### PR TITLE
fix: Many windows

### LINKED ISSUE #506: Many edit place dialogs for same place
When I go to edit a place, if I click on the edit button several times, it spawns multiple windows.
There should be one unique dialog that is brought to the front if it is already open.
Also, if I edit a place and mess with the style accordion options in the layers window there can be conflicting changes. (This last part is captured in #573 )

editEditEdit

0.5 story points

### PR DESCRIPTION
**Pull request by adamstja**
click of edit btn created multiple windows. now only one window.

fix #506

### CODE REVIEW

File: src/plugin/file/kml/ui/kmlnodeui.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ goog.require('plugin.file.kml.cmd.KMLNodeRemove');
 plugin.file.kml.ui.kmlNodeUIDirective = function() {
   return {
     restrict: 'E',
-    replace: true,
+    replace: false,
```
Comment (schmidtk) [inline src/plugin/file/kml/ui/kmlnodeui.js]: Why was this needed? We generally try to use `replace: true` because it prevents breaking the chain of flex items (the directive element will not have `d-flex`) which can cause layout problems.

File: src/plugin/file/kml/ui/kmlui.js [hunk 2]
```diff
@@ -110,6 +110,9 @@ plugin.file.kml.ui.createOrEditPlace = function(options) {
   };
 
   var label = (options['feature'] ? 'Edit' : 'Add') + ' Place';
+  if (os.ui.window.exists(windowId)) {
+    os.ui.window.bringToFront(windowId);
+  } else {
   var windowOptions = {
```
Comment (schmidtk) [inline src/plugin/file/kml/ui/kmlui.js]: This section isn't tabbed in, causing lint errors. Do you have eslint configured in your editor?

File: src/plugin/file/kml/ui/kmlui.js [hunk 3]
```diff
@@ -110,6 +110,9 @@ plugin.file.kml.ui.createOrEditPlace = function(options) {
   };
 
   var label = (options['feature'] ? 'Edit' : 'Add') + ' Place';
+  if (os.ui.window.exists(windowId)) {
```
Comment (schmidtk) [inline src/plugin/file/kml/ui/kmlui.js]: This currently causes strange behavior if I start creating a new place, then click edit on an existing place (the create window is brought to the front, when I'm expecting to get an edit window). Similarly if I click edit on one place, then click edit on another or try creating a new place.

This should use a unique id for creating a new place, and editing each existing place. I would suggest using the existing id for create, and for the edit case append `ol.getUid(options['feature'])` to the id.

File: src/plugin/places/placesmenu.js [hunk 4]
```diff
@@ -397,7 +397,7 @@ plugin.places.menu.visibleIfIsPlace = function(context) {
 plugin.places.menu.onSpatialEdit_ = function(event) {
   var features = os.ui.menu.spatial.getFeaturesFromContext(/** @type {Object} */ (event.getContext()));
   if (features.length === 1) {
-    var feature = features[0];
+    var feature = features[1];
```
Comment (schmidtk) [inline src/plugin/places/placesmenu.js]: This was correct as is. If the array length is 1, there will only be an item at index 0.

File: src/plugin/file/kml/ui/kmlui.js (hunk 3 above)
Comment (adamstja) [reply src/plugin/file/kml/ui/kmlui.js]: Sounds good. Random string was added to allow multiple new places to be created at the same time.
