### PR TITLE
Fix antimeridian queries via multiple world queries

### LINKED ISSUE #468: Spatial index query over antimeridian
`os.source.Vector` indexes spatially using an R-Tree (via the parent `ol.source.Vector`). That R-Tree uses extents normalized to the projection extent (longitudes in the range `[-180, 180]` for `EPSG:4326`). Extents that cross the antimeridian such as `[-190, -170]` or `[170, 190]` are thus cut off halfway through their range.

Potential solutions:
1. (Faster, more memory): Keep a second R-Tree with features indexed with their extents normalized to `[0, 360]` (the inverse from `[-180, 180]`). Any extent which crosses the antimeridian should use this R-Tree rather than the original.
1. (Slower, less memory): Split any extent crossing the antimeridian into two extents. Query the R-Tree for both extents and dedupe the resulting feature arrays.

Testing:
`os.source.Vector.getFeaturesInExtent`:
1. Load features over the antimeridian
1. Draw area over the antimeridian
1. Choose "Select"
1. Select the layer in the Layers window and turn on labels

`os.extent.getFunctionalExtent`
1. Load data only near the antimeridian
1. Right-click the layer and choose "Zoom"

### PR DESCRIPTION
**Pull request by wallw-bits**
Mixes in functionality to the OL RBush wrapper that queries for multiple 'worlds' of an extent and
dedupes those results.

Edit:
This now also addresses hit detection over the antimeridian from OpenLayers. A good test file for both of these items is
[KML Test.txt](https://github.com/ngageoint/opensphere/files/3074784/KML.Test.txt)

resolves #468

### CODE REVIEW

**Comment by wallw-bits** [comment]
This is marked WIP because it shouldn't be merged until being compared with the [other solution PR](#469).

File: src/os/ui/ol/interaction/dragboxinteraction.js [hunk 1]
```diff
@@ -93,14 +91,13 @@ os.ui.ol.interaction.DragBox.prototype.update = function(mapBrowserEvent) {
       this.extent = [];
     }
 
-    var start = ol.proj.toLonLat(this.startCoord, this.getMap().getView().getProjection());
-    var end = ol.proj.toLonLat(this.endCoord, this.getMap().getView().getProjection());
+    if (this.startCoord && this.endCoord) {
+      this.extent[0] = Math.min(this.startCoord[0], this.endCoord[0]);
```
Comment (schmidtk) [inline src/os/ui/ol/interaction/dragboxinteraction.js]: `update2D` expects the extent to be in lon/lat, so drag boxes are only working in 4326.
