### PR TITLE
fix(KMLExport): Unused options are removed from the export places.

### LINKED ISSUE #486: Export Places - Remove Unused Options
Export Places is intended to work in a way so that places are reimported with the exact same style (in Opensphere, Google Earth doesn't support our point/square/etc styles). Remove the following extraneous KML options because this is a very specific, tailored export:

- Use Feature Colors
- Export Ellipses
- Default Icon

### PR DESCRIPTION
**Pull request by lilysikes**
Resolves #486

### CODE REVIEW

File: src/plugin/file/kml/ui/kmlexportui.js [hunk 1]
```diff
@@ -17,7 +17,8 @@ plugin.file.kml.ui.kmlExportDirective = function() {
     restrict: 'E',
     scope: {
       'exporter': '=',
-      'simple': '=?'
+      'simple': '=?',
+      'savedplaces': '='
```
Comment (schmidtk) [inline src/plugin/file/kml/ui/kmlexportui.js]: Avoid referring to Saved Places anywhere outside the places plugin (`src/plugin/places`). I believe the `simple` attribute is already what you want, but it should also disable the `Use Feature Colors` option.
