### PR TITLE
fix(capture): fixed position/size errors on high DPI displays

### LINKED ISSUE #124: Screenshot capability may move overview dialog and overview results
image

with Save->Screenshot produced:
screenshot 2018-02-11_102043

Two issues:
 1. that the overview map has relocated on the map (potentially obscuring object of interest)
 2. that the overview map area of interest (the dashed red box) is now showing the wrong area (north and west of the actual area in the screenshot).

### PR DESCRIPTION
**Pull request by wallw-bits**
The `MapOverlayRenderer` was not properly sizing and positioning on high DPI displays such as Apple Retina devices. The pixel ratio is now calculated from the canvas and its bounding client rect and used in those calculations.

Resolves #124

### CODE REVIEW

File: src/plugin/capture/mapoverlayrenderer.js [hunk 1]
```diff
@@ -98,18 +91,23 @@ plugin.capture.MapOverlayRenderer.prototype.getCanvas = function() {
  * @inheritDoc
  */
 plugin.capture.MapOverlayRenderer.prototype.getPosition = function(canvas) {
-  var x;
-  var y;
+  var x = 0, y = 0;
```
Comment (bradh) [inline src/plugin/capture/mapoverlayrenderer.js]: Travis is showing a few errors that seem relevant:
```
/home/travis/build/ngageoint/opensphere/src/plugin/capture/mapoverlayrenderer.js
  78:11  error  Expected indentation of 12 spaces but found 10     indent
  79:11  error  Expected indentation of 12 spaces but found 10     indent
  80:11  error  Expected indentation of 12 spaces but found 10     indent
  81:11  error  Expected indentation of 12 spaces but found 10     indent
  94:3   error  Split 'var' declarations into multiple statements  one-var
```
