### PR TITLE
fix(style): fix merge to allow fill and outline deletions

### LINKED ISSUE #604: Support filled polygon without an outline
There are two issues at play here:

1. The KML importer [merges the default style config](https://github.com/ngageoint/opensphere/blob/master/src/plugin/file/kml/kmlparser.js#L1430) into the style config generated from the KML style. This means KML styles that do not have an outline defined will get a white outline from the default style. This line should either be removed, or improved to verify the minimum default styles to render the geometry are available in the config.
2. In `os.style.createFeatureConfig`, we merge the stroke style from the layer config if one isn't present on the feature config. Determine why this was needed and remove it if possible, otherwise make the implementation more specific to the problem it was intended to solve.

### PR DESCRIPTION
**Pull request by wallw-bits**
This changes the style config merging to allow for a definition of `null` to remove the parent style rather than inheriting it (`undefined`). Additionally, the `readStyle_` parser in `ol.format.KML` was replaced with a custom implementation which returns style configs rather than OpenLayers style objects.

Example: create a style config that removes a stroke rather than inheriting the default stroke:
```
var styleConfig = {
  'fill': {
    'color': 'rgba(255,0,0,1)',
  },
  'stroke': null
};
```

Testing:
Compare [PolygonStyles.txt](https://github.com/ngageoint/opensphere/files/3302618/PolygonStyles.txt) to the same file in Google Earth (making labels always on helps with identifying the correct style)

Google Earth result:
Screen Shot 2019-06-13 at 12 15 52 PM

resolves #604

### CODE REVIEW

**Comment by justin-bits** [comment]
Build failure addressed by #623

File: src/plugin/file/kml/kmlparser.js [hunk 1]
```diff
@@ -1396,41 +1392,42 @@ plugin.file.kml.KMLParser.reduceStyles_ = function(config, set) {
...
+  var styles = [];
   var highlightStyle = null;
 
   // style from style url
   var styleUrl = /** @type {string} */ (feature.get('styleUrl'));
   if (styleUrl) {
     var styleId = this.getStyleId(decodeURIComponent(styleUrl));
-    styleSets.push(styleId in this.styleMap_ ? this.styleMap_[styleId] : null);
+    styles.push(styleId in this.styleMap_ ? this.styleMap_[styleId] : null);
     highlightStyle = styleId in this.highlightStyleMap_ ? this.highlightStyleMap_[styleId] : null;
```
Comment (schmidtk) [inline src/plugin/file/kml/kmlparser.js]: With the `readStyle` change, `this.highlightStyleMap_` will now be `<string, Object>`. That needs to be updated in the JSDoc and accounted for when setting the custom highlight on the feature.

File: src/os/style/style.js [hunk 2]
```diff
@@ -1251,6 +1251,10 @@ os.style.createFeatureStyle = function(feature, baseConfig, opt_layerConfig) {
 os.style.mergeConfig = function(from, to) {
   for (var key in from) {
     var fval = from[key];
+    if (fval === os.object.IGNORE_VAL) {
+      continue;
+    }
+
     if (fval && typeof fval == 'object' && !(typeof fval.length == 'number')) {
       // clone objects into the target
       if (!(key in to)) {
```
Comment (schmidtk) [inline src/os/style/style.js]: This needs to handle `to[key]` being `null` or `undefined`. This is causing an error when hovering the polygons without a stroke, because it tries merging the highlight stroke into `null`.

File: src/plugin/file/kml/kmlparser.js (hunk 1 above)
Comment (wallw-bits) [reply src/plugin/file/kml/kmlparser.js]: I'm surprised the compiler didn't complain about that.

File: src/os/style/style.js (hunk 2 above)
Comment (wallw-bits) [reply src/os/style/style.js]: Fixed and added tests. `undefined` was already handled.
